spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/notice_check
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false

server:
  port: 8080
  error:
    include-stacktrace: never
    include-message: never

logging:
  level:
    root: INFO
    com.example.NoticeCheck: INFO
  file:
    name: /var/log/noticecheck/application.log 